name: Build and deploy Node.js app to Azure Web App - ticket-booking-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --production

      - name: Run tests (optional)
        run: npm test --if-present

      - name: Zip artifact for deployment
        run: |
          # Exclude files not needed in production
          zip -r release.zip . -x *.git* node_modules/\* .env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C94DC7FFEE44CC1B38EA3067E537274 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D6DC4BD2883C42BBB1F7C907B57725BA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_510665DBEE9B43EEBE7460152888B51C }}

      - name: Install production dependencies
        run: npm install --production

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ticket-booking-backend'
          slot-name: 'Production'
          package: .
